### ISSUE TITLE
百度雲鏈接失效

### ISSUE THREAD

**Issue by kaneyxx** [Sophia-11/Machine-Learning-Notes#4]
在AI視覺聯盟回覆後拿到的百度雲鏈接是失效的，請問該如何反應
btw, 感謝分享這麼棒的筆記～

**Comment by Sophia-11** [comment]
您好，刚刚我已经在后台回复您新的下载链接了

**Comment by kaneyxx** [comment]
有看到你的訊息，不過點下去都寫頁面不存在...好奇怪

**Comment by kaneyxx** [comment]
我改用手機開可以連上，網頁不知道為什麼都不行...
很謝謝你的幫忙，我下載了
